version = 0.1
[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "testing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pxsxu1639hbv"
s3_prefix = "testing"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "true-fi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j7u82pp4a6fy"
s3_prefix = "true-fi"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
