AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for True-Fi Lambda Functions

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 600

Resources:
  GetLogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Logs.getLogs
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
  GetLoansFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Loans.getLoans
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetLoans:
          Type: Api
          Properties:
            Path: /loans
            Method: post
  GetVoteEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: VoteEvents.getAllVotes
      CodeUri: api/
      Events:
        GetLVotes:
          Type: Api
          Properties:
            Path: /votes
            Method: post
  GetTfiPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TfiPrice.getTfiPrice
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetTfiPrice:
          Type: Api
          Properties:
            Path: /tfi-price
            Method: get
  GetTruPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TruPrice.getTruPrice
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetTruPrice:
          Type: Api
          Properties:
            Path: /tru-price
            Method: get
  GetApyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Apy.getApy
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetApy:
          Type: Api
          Properties:
            Path: /apy
            Method: post
  GetTruFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Tru.getTru
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetTru:
          Type: Api
          Properties:
            Path: /tru
            Method: get
  GetPoolValuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PoolValues.getPoolValues
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetPoolValues:
          Type: Api
          Properties:
            Path: /pool-values
            Method: get
  GetPoolValueChartDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Pool/GetPoolValueChart.index
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetPoolValueHelpers:
          Type: Api
          Properties:
            Path: /pool-value-chart
            Method: get
  GetPoolInteractionChartDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Pool/GetInteractionChart.index
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetPoolInteractionHelpers:
          Type: Api
          Properties:
            Path: /pool-interaction-chart
            Method: get
  GetPoolCompositionChartDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Pool/GetCompositionChart.index
      CodeUri: api/
      Layers:
        - !Ref UtilityHelpers
      Events:
        GetPoolCompositionHelpers:
          Type: Api
          Properties:
            Path: /pool-composition-chart
            Method: get
            
  UtilityHelpers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: UtilityLayer
      ContentUri: layers/
      CompatibleRuntimes:
        - nodejs12.x