AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  True-Fi

  SAM Template for True-Fi Lambda Functions

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 600

Resources:
  GetLogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Logs.getLogs
      CodeUri: api/
      Events:
        GetLoan:
          Type: Api
          Properties:
            Path: /logs
            Method: get
  GetLoansFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Loans.getLoans
      CodeUri: api/
      Events:
        GetLoan:
          Type: Api
          Properties:
            Path: /loans
            Method: post
  GetVoteEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: VoteEvents.getAllVotes
      CodeUri: api/
      Events:
        GetLoan:
          Type: Api
          Properties:
            Path: /votes
            Method: post
  GetTfiPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TfiPrice.getTfiPrice
      CodeUri: api/
      Events:
        GetLoan:
          Type: Api
          Properties:
            Path: /tfi-price
            Method: get
  GetTruPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: TruPrice.getTruPrice
      CodeUri: api/
      Events:
        GetLoan:
          Type: Api
          Properties:
            Path: /tru-price
            Method: get
  GetApyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Apy.getApy
      CodeUri: api/
      Events:
        GetApy:
          Type: Api
          Properties:
            Path: /apy
            Method: post
  GetTruFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Tru.getTru
      CodeUri: api/
      Events:
        GetTru:
          Type: Api
          Properties:
            Path: /tru
            Method: get
  GetPoolValuesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PoolValues.getPoolValues
      CodeUri: api/
      Events:
        GetTru:
          Type: Api
          Properties:
            Path: /pool-values
            Method: get